### ISSUE TITLE
Keyerror for hosts that don't exist

### ISSUE THREAD

**Issue by shebang42** [n3ko1/WrapMap#1]
Nice tool!  However, for hosts that do not exist, the script terminates with a 'keyerror'

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/paul/enum/tools/WrapMap/nmap.py", line 412, in scan_progressive
    callback(host, scan_data)
  File "./WrapMap.py", line 122, in nmapScanComplete
    host_result = scan_result['scan'][host]
KeyError: u'192.168.xx.x2'
<I've replaced last tuples with x>

I've added an extra print command in the nmap.py wrapper on line 410:

409                 if callback is not None and callable(callback):
410                     print host, callable(callback), scan_data
411                     callback(host, scan_data)

As you can see below, 'scan' is empty.
Output 1: Host does exist:

192.168.xx.x1 True {'nmap': {'scanstats': {'uphosts': u'1', 'timestr': u'Thu Aug  6 20:26:27 2015', 'downhosts': u'0', 'totalhosts': u'1', 'elapsed': u'5.58'}, 'scaninfo': {u'tcp': {'services': u'1-65535', 'method': u'connect'}}, 'command_line': u'nmap -oX - -sT -p 1-65535 192.168.xx.x1'}, 'scan': {u'192.168.xx.x1': {'status': {'state': u'up', 'reason': u'conn-refused'}, 'hostname': u'vbox01.home', u'tcp': {22: {'state': u'open', 'reason': u'syn-ack', 'name': u'ssh'}}}}} 

Output 2: Host does not exist (no arp, no ping...)
192.168.xx.x2 True {'nmap': {'scanstats': {'uphosts': u'0', 'timestr': u'Thu Aug  6 20:28:23 2015', 'downhosts': u'1', 'totalhosts': u'1', 'elapsed': u'3.04'}, 'scaninfo': {u'tcp': {'services': u'1-65535', 'method': u'connect'}}, 'command_line': u'nmap -oX - -sT -p 1-65535 192.168.xx.x2'}, 'scan': {}} 

Checking for this in Wrapmap.py on line 122 seems to fix the problem.  However, I am not sure if this is the right place to add a check.  I suspect that something goes wrong in the nmap.py script.

121     def nmapScanComplete(self, host, scan_result):
122         if scan_result['scan']:
123             host_result = scan_result['scan'][host]
124         else:
125             return

Thanks!
-Paul.

**Comment by lcsbdr** [comment]
Hi Paul,

thanks for your feedback, I really appreciate it! You're right that something goes wrong in the nmap.py library. If a host is down or non-existant, it should return the state within the 'scan' result. However, since I am using an older version of the python-nmap library for Python 2.x compatibility, this bug may be fixed in later versions.

As I don't want to greatly modify the python-nmap nmap.py (in order to allow for updates to later versions of the library), I implemented the fix you recommended. Thanks!
